### PR TITLE
Prisma Kysely v2.0.0

### LINKED ISSUE #69: Prisma kysely not generating, Error: spawn prisma-kysely ENOENT
Hi, Iam having trouble generating types 

this is my schema file I want to build both prisma and Kysely types.

```ts
generator client {
  provider = "prisma-client-js"
}

generator kysely {
  provider = "prisma-kysely"

  // Optionally provide a destination directory for the generated file
  // and a filename of your choice
  output       = "../src/db"
  fileName     = "types.ts"
  // Optionally generate runtime enums to a separate file
  enumFileName = "enums.ts"
}
```
I am using prisma 5 and prisma-kysely version 1.6

this is the error 
image

what am I doing wrong?

### LINKED ISSUE #88: Support for node16 and nodenext module resolution
Hi there,

The generated types.ts file is importing ./enums. When using node16 or nodenext the import should be ./enums.js.

The error is:

> error TS2835: Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Did you mean './enums.js'?

### LINKED ISSUE #91: Support renaming the `DB` export
In my project I have two databases and I always have to select the correct generated `DB` type. It would be awesome if I could provide different names through the generator config.

### LINKED ISSUE #94: Format generated file using latest prettier broken
Due to this breaking changes https://github.com/prettier/prettier/issues/15879 
Generated kysely files is not being formatted using prettier anymore.

### LINKED ISSUE #96: Upgrade vulnerable dependencies
Currently, the package depends on @primsa/internals 5.3.1. Is there a plan to upgrade all dependencies on a regular basis to resolve vulnerabilities?

### LINKED ISSUE #106: Support multiple schemas
When [multiSchema](https://www.prisma.io/docs/orm/prisma-schema/data-model/multi-schema) is enabled, it's possible to have tables of the same name in different schemas. Right now, `prisma-kysely` will export the `DB` interface with duplicate properties.

It would be great to namespace the tables with their schema, such as `my_other_schema.example_table`. (This is what [`kysely-codegen`](https://github.com/RobinBlomberg/kysely-codegen) does.)

### LINKED ISSUE #115: Using PNPM is showing Error: Generator "prisma-kysely" failed:
Pnpm command: (NOT WORKING)
pnpm dlx prisma migrate dev
...(migrating works good)
Running generate... (Use --skip-generate to skip the generators)
Error: Generator "prisma-kysely" failed:

/bin/sh: 1: prisma-kysely: not found

npm command: (WORKING)
npx prisma migrate dev
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "api", schema "public" at "localhost:5432"

Already in sync, no schema change or pending migration was found.

✔ Generated Kysely types (1.8.0) to ./src/db in 58ms

### LINKED ISSUE #116: Is this project abandoned?
I'm trying to figure out if this project is maintained or not, because I've been using a Prisma schema (and Prisma for migrations) and Kysely for querying, but if the project is abandoned I'll bump into issues eventually, so I'll have to migrate away from it.

### LINKED ISSUE #117: Depending on vulnerable Prisma version
Apparently, the project depends on a vulnerable version of `prisma/internals (5.3.1)`. This vulnerability is related to a [Regular Expression Denial of Service (ReDoS) in cross-spawn](https://github.com/advisories/GHSA-3xgq-45jj-v275).

I suggest updating to `Prisma 6.0`. However, my concern is whether the breaking changes in this upgrade will have any impact on this library.

### PR DESCRIPTION
**Pull request by arthurfiorette**
closes #91
closes #88
closes #69
closes #96
closes #106
closes #115
closes #116
closes #117
closes #94
closes #97
closes #100

Previously, this was a PR created to introduce `groupBySchema`. However, [following recent discussions on Kysely discord](https://discord.com/channels/890118421587578920/1372956350463606885), this PR now is home to all work for the upcoming prisma release v2.0.0

<details>
<summary>Old description</summary>

closes #91 

I didn't need to fix any test after adding this feature, this means that everything kept running exactly as before when `groupBySchema` is not `true`.

We are using this plugin in a giant schema (100+ tables under 18 schemas) where some of them have the same or similar names, which is very hard to spot visually which schema an imported type comes from.

This plugin simply adds all enums and models under a `ts.ModuleDeclaration` respective to their schema and fixes types references to it. It makes it much easier to work with schemas, the same visually/architecturally as thinking about why schemas are written like `schema.model` inside SQL.

---

EDIT: I also added `filterBySchema`, which just picks all models from defined schemas.

---

```prisma
generator kysely {
    provider        = "node ./dist/bin.js"
    previewFeatures = ["multiSchema"]
    groupBySchema   = true
}

datasource db {
    provider = "postgresql"
    schemas  = ["mammals", "birds", "world"]
    url      = env("TEST_DATABASE_URL")
}

model Elephant {
    id      Int     @id
    name    String
    ability Ability @default(WALK)
    color   Color

    @@map("elephants")
    @@schema("mammals")
}

model Eagle {
    id      Int     @id
    name    String
    ability Ability @default(FLY)

    @@map("eagles")
    @@schema("birds")
}

enum Ability {
    FLY
    WALK

    @@schema("world")
}

enum Color {
    GRAY
    PINK

    @@schema("mammals")
}
```

Now generates:

```ts
export namespace World {
  export const Ability = {
    FLY: "FLY",
    WALK: "WALK",
  } as const;
  export type Ability = (typeof Ability)[keyof typeof Ability];
}
export namespace Mammals {
  export const Color = {
    GRAY: "GRAY",
    PINK: "PINK",
  } as const;
  export type Color = (typeof Color)[keyof typeof Color];
  export type Elephant = {
    id: number;
    name: string;
    ability: Generated<World.Ability>;
    color: Mammals.Color;
  };
}
export namespace Birds {
  export type Eagle = {
    id: number;
    name: string;
    ability: Generated<World.Ability>;
  };
}
export type DB = {
  "birds.eagles": Birds.Eagle;
  "mammals.elephants": Mammals.Elephant;
};
```

Instead of putting everything globally as previously:

```ts
export const Ability = {
  FLY: "FLY",
  WALK: "WALK",
} as const;
export type Ability = (typeof Ability)[keyof typeof Ability];
export const Color = {
  GRAY: "GRAY",
  PINK: "PINK",
} as const;
export type Color = (typeof Color)[keyof typeof Color];
export type Eagle = {
  id: number;
  name: string;
  ability: Generated<Ability>;
};
export type Elephant = {
  id: number;
  name: string;
  ability: Generated<Ability>;
  color: Color;
};
export type DB = {
  "birds.eagles": Eagle;
  "mammals.elephants": Elephant;
};
```

</details>

### CODE REVIEW

**Comment by arthurfiorette** [comment]
I've published this PR as `@arthurfiorette/prisma-kysely@1.9.0` if anyone wants it

**Comment by Bathlamos** [comment]
I tried your implementation on a schema with a hundred tables and it works fine. ESLint complains about the use of namespaces, which aren't necessary anyway as Prisma already forces the model names to be distinct even if they are in different schemas. Another interesting avenue of improvement might be to designate a schema as default, e.g. the `public` schema, to avoid prefixing its models.

**Comment by arthurfiorette** [comment]
Hey @Bathlamos, I just added a `defaultSchema` option!

**Comment by igalklebanov** [comment]
Hey 👋 

I think that the use of `namespaces` should be replaced with a file (module) per PostgreSQL schema.
If people still want that namespace syntax when consuming, they can just:

```ts
import * as Public from 'path/to/public/schema/types'

Public.Person
```

More shorter files = better performance as seen with https://www.prisma.io/docs/orm/prisma-schema/overview/generators#output-splitting-and-importing-types.

**Comment by arthurfiorette** [comment]
In general, `* as Public` and other forms of non-named exports don't work well with IntelliSense or auto-imports, unless we manually emit both JS and DTS files using the `export as namespace` syntax. However, doing so would significantly deviate from the current plugin architecture.

Also, the output generated by `prisma-kysely` differs from Prisma in that Prisma emits a large number of complex type definitions per model. In contrast, `prisma-kysely` provides a straightforward 1:1 mapping. So unless we're dealing with thousands of database models, performance shouldn't be a concern here.

Namespaces are often considered problematic when declared across multiple files, as that can make it harder for the TypeScript type checker to do its job efficiently. However, that doesn't seem to be the case here also.

Given all of the above, I still believe using namespaces is the right approach here.

**Comment by arthurfiorette** [comment]
Hey @igalklebanov!

> the team recommending https://github.com/microsoft/TypeScript/issues/30994#issuecomment-492017219

As far as I understood, that comment points out problems that happens when using namespaces across multiple files. _(As the typescript team suffered that personally since TS's own codebase was structured as a few giant namespaces)_

It was easy to implement namespaces here because of our current architecture as we can simply reuse everything already made and wrap the result with an `ts.factory.createModuleDeclaration()`. 

It also said:

- "If you have code that you feel needs to use a namespace, **_more power to you and go for it_**, but most of the time you don't need one, as we now have a different conceptual organizational model recommended for **_large-scale JS (modules)_**"

> eslint yelling at people in [the recommended ruleset](https://typescript-eslint.io/rules/no-namespace/)

We have eslint rules to disallow/enforce almost everything. Ideally, generated files should not be linted. Is there something more personal than linting rules?

> This is a DX problem.

DX usually means a combination of personal preference and familiarity.

> So either provide both.

I'd love to later help you by reviewing a PR adding support your alternative :)

> Another reason to avoid them?

The problem said states something that does not happens in this use-case: 1 single file with 1 model per file.

---

I'll never be against new features but personal preferences does not seems a compelling use case since the current implementation does not seems worse ihmo.

Although using `import * as Group` and emitting multiple files would require an interesting rewrite of `generateFile.ts` and all the known problems when correctly generating import statements across multiple files for many cjs/esm tsconfig variants.

As far as my knowledge goes into the type checker and compiler internals, enabling `isolatedModules` makes namespace declarations type-checking behavior almost identical as if types were declared in the file root _(Although I might be wrong here)_.

**Comment by igalklebanov** [comment]
> As far as I understood, that comment points out problems that happens when using namespaces across multiple files. (As the typescript team suffered that personally since TS's own codebase was structured as a few giant namespaces)

> It also said:
> 
> "If you have code that you feel needs to use a namespace, more power to you and go for it, but most of the time you don't need one, as we now have a different conceptual organizational model recommended for large-scale JS (modules)" 

This is not about namespaces, but the public perception of them, prominent tooling recommending against their usage, and the majority of TypeScript developers not wanting them in their codebases as a result.

Forcing them, by surprise, as the only way, is not good DX, and is fighting against the grain.

No amount of cherry-picking is going to help the case for them.

> We have eslint rules to disallow/enforce almost everything.

But this one is in the recommended preset of a linter that's downloaded 48,854,801 times per week. How many people care enough (about namespaces) to tinker with the recommended preset and allow them?

> Ideally, generated files should not be linted. Is there something more personal than linting rules?

How many people configure their tooling properly? How many headaches will this cause?

> I'd love to later help you by reviewing a PR adding support your alternative :)

I didn't mean to demand anything. This is just how I talk sometimes. :)

**Comment by alii** [comment]
I think namespaces are suitable here

Ultimately I believe it's unfortunate that no-namespaces was a default/recommended rule for the TypeScript eslint plugin. I personally usually turn that one off.

Additionally namespaces are a pretty similar representation in TypeScript of what it means to have a database schema. While separate files do represent some separation to some degree, I would say namespaces are a closer match in terms of what they semantically represent.

Could the solution be that we have a `// eslint-disable` comment at the top of file? It sounds like the only issue with using namespaces is that people using ESLint will see errors in the file.

File: src/utils/camelCase.ts
Comment (alii) [inline src/utils/camelCase.ts:1]: Maybe rename from camelCase.ts to `words.ts` or `casing.ts` or `letters.ts` or something similar

**Review by alii — CHANGES_REQUESTED** [review]
The changes seem reasonable to me and test coverage makes sense.

Just a couple of nits I've left a comment on.

Separately I've left a PR on your fork @arthurfiorette - https://github.com/arthurfiorette/prisma-kysely/pull/1 which I think we could merge before _this_ PR merges, as part of the current effort to bring prisma-kysely back to life.

File: src/utils/validateConfig.ts [hunk 1]
```diff
@@ -40,12 +40,28 @@ export const configValidator = z
...
     readOnlyIds: booleanStringLiteral.default(false),
+
+    // Group models in a namespace by their schema. Cannot be defined if enumFileName is defined.
+    groupBySchema: booleanStringLiteral.default(false),
+
+    // Which schema should not be wrapped in a namespace
+    defaultSchema: z.string().default("public"),
+
+    // Group models in a namespace by their schema. Cannot be defined if enumFileName is defined.
+    filterBySchema: z.array(z.string()).optional(),
```
[the remark this answers is not in the document]
Comment (arthurfiorette) [reply src/utils/validateConfig.ts:51]: I did change the readme.

image

**Comment by igalklebanov** [comment]
> I think namespaces are suitable here
> 
> In my opinion I believe it's unfortunate that no-namespaces was a default/recommended rule for the TypeScript eslint plugin. I personally usually turn that one off.
> 
> Additionally namespaces are a pretty similar representation in TypeScript of what it means to have a database schema. While separate files do represent some separation to some degree, I would say namespaces are a closer match in terms of what they semantically represent.

Similar to what I replied to @arthurfiorette, namespaces are not the issue here. It's the negative public perception, following what was said and done about them for years. What's done is done.

> Could the solution be that we have a `// eslint-disable` comment at the top of file? It sounds like the only issue with using namespaces is that people using ESLint will see errors in the file.

You'd also need to provide a disable comment for `biome`, just in case some people explicitly enable `lint/style/noNamespace`.

It wouldn't solve it for people who configure [noInlineConfig](https://eslint.org/docs/latest/use/configure/rules#disabling-inline-comments).

But linters are not the only issue. Negative public perception of namespaces means people might not like `prisma-kysely` shoving unwanted syntax in their codebase, without providing alternatives. Imagine Colin forcing people to use TypeScript string enums (which he likes btw) in Zod v4 as the only way for users to achieve a certain goal.

**Comment by valtyr** [comment]
I don't have a particularily strong opinion for or against namespaces as long as we're not breaking any behavior people are used to from the library.

In regards to the linting issue: this could be solved with an option to prepend text to the generated file. I feel like that's the solution I expect from codegen libraries. That way people can add ignore comments for the tools that they use, and we won't have to assume anything.

File: src/helpers/multiSchemaHelpers.test.ts [hunk 2]
```diff
@@ -27,18 +30,55 @@ model Eagle {
...
+  ]);
+});
+
+test("returns a list of models with schemas appended to the table name filtered by schema", () => {
+  const initialModels = [
+    { typeName: "Elephant", tableName: "elephants" },
+    { typeName: "Eagle", tableName: "eagles" },
+  ];
+
+  const result = convertToMultiSchemaModels(
```
Comment (alii) [inline src/helpers/multiSchemaHelpers.test.ts:73]: nitpick: `convertToMultiSchemaModels` could also accept an options object as it's again hard to quickly scan what the arguments here are
```suggestion
  const result = convertToMultiSchemaModels(
```

File: src/helpers/generateModel.test.ts [hunk 3]
```diff
@@ -83,18 +83,24 @@ test("it generates a model!", () => {
...
       enumFileName: "",
       camelCase: false,
       readOnlyIds: false,
-    }
+      groupBySchema: false,
+      defaultSchema: "public",
+      dbTypeName: "DB",
+    },
+    false,
+    "public"
```
Comment (alii) [inline src/helpers/generateModel.test.ts:103]: Nitpick: generateModel should/could accept an options object instead here. The new arguments here are hard to immediately understand when scanning usages of this function.
```suggestion
      groupBySchema: false,
      defaultSchema: "public",
      dbTypeName: "DB",
    },
    false,
    "public"
```

File: src/helpers/generateEnumType.ts [hunk 4]
```diff
@@ -6,10 +6,22 @@ import isValidTSIdentifier from "~/utils/isValidTSIdentifier";
...
+
+export const generateEnumType = (
+  name: string,
+  values: readonly DMMF.EnumValue[]
+): EnumType | undefined => {
   const type = generateStringLiteralUnion(values.map((v) => v.name));
 
-  if (!type) return [];
+  if (!type) {
+    return undefined;
```
Comment (alii) [inline src/helpers/generateEnumType.ts:23]: Is it more-correct to throw in this case? Or a better question to ask is "do we ned make sure an error is surfaced to the user here?"

I ask because there's code that uses generateEnumType (which can return undedfined) that does a check for `!!value` instead of potentially showing a warning/erroring

**Comment by arthurfiorette** [comment]
Hey @frannyfx, just letting you know that I copied your #100 PR into this one so we can avoid merge conflicts and ship your fix as fast as possible.

File: src/helpers/generateEnumType.ts (hunk 4 above)
Comment (alii) [reply src/helpers/generateEnumType.ts:23]: The fact that `generateStringLiteralUnion` *could* return null means we should just surface the error in the case we do reach that condition, for whatever possible reason.  I think it's fine to just throw here

Comment (arthurfiorette) [reply src/helpers/generateEnumType.ts:23]: Why break their entire schema generation when we can just skip the empty enum?

**Comment by alii** [comment]
Let's get this merged. Thank you very much @arthurfiorette for all your efforts working on these changes ❤️
